version: '3.8'

services:
  backend:
    environment:
      - ENVIRONMENT=production
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    environment:
      - NODE_ENV=production
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
